version: '3'

services:
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
            - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
        container_name: poklikv2

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8002:80"
        depends_on:
            - db
        container_name: poklikv2_nginx

    db:
        image: mysql:latest
        container_name: poklikv2_db
        restart: always
        environment:
            MYSQL_DATABASE: poklikv2
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8006:3306"

    phpmyadmin:
        container_name: poklikv2_phpmyadmin
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
        ports:
            - "8007:80"
